modules/blog/controllers/NewsController.php
<?php

namespace app\modules\blog\controllers;

use app\models\Comment;
use app\models\NewsComment;
use app\models\NewsLike;
use app\modules\blog\models\forms\CommentForm;
use app\modules\blog\models\forms\NewsSearchForm;
use app\modules\blog\models\Rubric;
use app\modules\blog\models\RubricNews;
use app\modules\blog\models\RubricSearch;
use Yii;
use app\modules\blog\models\News;
use app\modules\blog\models\NewsSearch;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller{

    /**
     * @inheritdoc
     */
    public function behaviors(){

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @inheritDoc
     * @param $action
     * @return bool|Response
     */
    public function beforeAction($action){

        $model = new NewsSearchForm();
        if($model->load(Yii::$app->request->get()) && $model->validate()){
            $search = Html::encode($model->search);
            return $search ? $this->redirect(['/blog/news/index', 'search' => $search]) : $this->redirect(['/blog/news/index']);
        }
        return true;
    }

    /**
     * Lists all News models.
     *
     * @param string $rubric слаг рубрики
     * @param string $search поисковый запрос
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionIndex($rubric = null, $search = null){

        $rubrics = Rubric::find()->all();
        $Rubric = null;
        if($rubric){
            if(!$Rubric = Rubric::findOne(['slug' => $rubric])){
                throw new NotFoundHttpException('Страница не найдена');
            }
        }
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $Rubric);
        $news_count = $searchModel->search(Yii::$app->request->queryParams, $Rubric, true);

        $modelsPks = ArrayHelper::getColumn($dataProvider->models, 'id');

        $rightDataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $rightDataProvider->query->orderBy('date_published desc');
        $rightDataProvider->query->andWhere(['!=', 'main_news', 1]);
        $rightDataProvider->query->andWhere(['status_published' => 1]);
        $rightDataProvider->query->offset(4);
        $rightDataProvider->query->limit(9);
        $rightDataProvider->query->andWhere(['not in', 'id', $modelsPks]);

//        $expressDataProvider = $searchModel->search(Yii::$app->request->queryParams);
//        $expressDataProvider->query->orderBy('date_published desc');
//        $expressDataProvider->query->andWhere(['status_published' => 1]);
//        $expressDataProvider->query->andWhere(['is_express' => 1]);
//        $expressDataProvider->query->limit(3);

        $expressNews = News::find()->where(['status_published' => 1, 'is_express' => 1])->orderBy('date_published desc')->limit(3)->all();
        $expressDataProvider = new ArrayDataProvider(['models' => $expressNews]);

//        $popularDataProvider = $searchModel->search(Yii::$app->request->queryParams);
//        $popularDataProvider->query->orderBy('count_news desc');
//        $popularDataProvider->query->andWhere(['status_published' => 1]);
//        $popularDataProvider->pagination->limit = 3;

        $popularNews = News::find()->where(['status_published' => 1, 'is_express' => 1])->orderBy('date_published desc')->limit(3)->all();
        $popularDataProvider = new ArrayDataProvider(['models' => $popularNews]);

        $importantNews = News::find()->where(['status_published' => 1, 'is_important' => 1])->orderBy('date_published desc')->limit(3)->all();
        $importantDataProvider = new ArrayDataProvider(['models' => $popularNews]);

        $mainNew = News::findOneMain();
        $mainRubrics = ArrayHelper::index(Rubric::findAll(['id' => [2, 3, 4]]), 'id');

        return $this->render('index', compact('rubrics', 'search', 'searchModel', 'dataProvider', 'rightDataProvider', 'expressDataProvider', 'popularDataProvider', 'importantDataProvider', 'mainNew', 'Rubric', 'news_count', 'mainRubrics'));
    }

    public function actionModeration()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['or', ['status_published' => 0], ['status_published' => null]]);

        return $this->render('moderate', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param string $title
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($title){

        if(!$model = News::find()->where(['english_title' => $title])->one()){
            throw new NotFoundHttpException('Страница не найдена');
        }
        $searchModel = new NewsSearch();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//        $dataProvider->query->orderBy('date_published desc');
//        $dataProvider->query->andWhere(['!=', 'main_news', 1]);
//        $dataProvider->query->andWhere(['status_published' => 1]);
//        $dataProvider->query->andWhere(['!=', 'id', $model->id]);
//        $dataProvider->query->limit(9);
//        $dataProvider->pagination = false;

        $model->updateCountView();
        $rubrics = RubricNews::find()->where(['news_id' => $model->id])->all();
        $comments_query = NewsComment::find()->where(['new_id' => $model->id])->orderBy('created_at desc');
        if(!Yii::$app->request->post('comment_limit')){
            $comments_query->limit(3);
        }
        $comments = $comments_query->all();
        $comments_count = NewsComment::find()->where(['new_id' => $model->id])->count();
        $commentForm = new CommentForm();
        if($commentForm->load(Yii::$app->request->post()) && !Yii::$app->request->post('comment_limit')){
            if($commentForm->validate()){
                $commentForm->saveComment($model);
            }else{
                Yii::error(print_r($commentForm->getErrors(), true));
            }
            return $this->redirect(['view', 'title' => $title]);
        }
        return $this->render('view', compact('model', 'searchModel', 'rubrics', 'comments', 'comments_count', 'commentForm'));
    }

    /**
     * @param int $id
     * @return mixed
     */
    public function actionComments($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $comments = NewsComment::find()->where(['new_id' => $id])->all();

        return $comments;
    }

    /**
     * @return array
     */
    public function actionAddComment()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new NewsComment();

        if($model->load(Yii::$app->request->post()) && $model->save()){
            return ['success' => true];
        } else {
            return ['success' => false, 'errors' => $model->errors];
        }
    }

    /**
     * Добавление/удаление лайка
     *
     * @param integer $id
     * @return int|string
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionAddLike($id){

        if(Yii::$app->request->isAjax){
            if(!News::find()->where(['id' => $id])->exists()){
                throw new NotFoundHttpException('Страница не найдена');
            }
            if($Like = NewsLike::find()->where(['new_id' => $id, 'user_id' => Yii::$app->user->identity->getId()])->one()){
                $Like->delete();
                return NewsLike::find()->where(['new_id' => $id])->count();
            }else{
                $Like = new NewsLike();
                $Like->new_id = $id;
                $Like->user_id = Yii::$app->user->identity->getId();
                if($Like->save()){
                    return NewsLike::find()->where(['new_id' => $id])->count();
                }
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return array
     * @throws NotFoundHttpException
     */
    public function actionUpdateComment($id){

        if(!$model = NewsComment::findOne(['id' => $id])){
            throw new NotFoundHttpException('Страница не найдена');
        }
        if($comment = Yii::$app->request->post('comment')){
            $model->content = $comment;
            if(!$model->save()){
                Yii::error(print_r($model->getErrors(), true));
                return false;
            }
            return $model->content;
        }
    }

    /**
     * @param int $id
     * @return false|int
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDeleteComment($id){

        if(!$model = NewsComment::findOne(['id' => $id])){
            throw new NotFoundHttpException('Страница не найдена');
        }
        return $model->delete();
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();
        $rubric = new Rubric();

modules/blog/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;

?>
<script async="" src="https://www.google-analytics.com/analytics.js"></script>
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<div class="content" <?php if(Yii::$app->controller->id == 'dashboard'): ?>style="width: 70%;"<?php endif; ?> id="content">

        <?php Pjax::begin(['enablePushState' => false, 'id' => 'report-messages-pjax']) ?>
        <?php if(Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success fade in m-b-15">
                <strong>Успех!</strong>
                <?=Yii::$app->session->getFlash('success')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('info')): ?>
            <div class="alert alert-info fade in m-b-15">
                <strong>Уведомление!</strong>
                <?=Yii::$app->session->getFlash('info')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('warning')): ?>
            <div class="alert alert-warning fade in m-b-15">
                <strong>Внимание!</strong>
                <?=Yii::$app->session->getFlash('warning')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-danger fade in m-b-15">
                <strong>Ошибка!</strong>
                <?=Yii::$app->session->getFlash('error')?>
                <span class="close" data-dismiss="alert">×</span>
                <div>

                </div>
            </div>
        <?php endif; ?>
        <?php Pjax::end() ?>

        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1 class="page-header">Basic Tables</h1>
        <?php } else { ?>
        <?php } ?>

<!--         <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?> -->

        <?= $content ?>
    </div>

modules/blog/views/layouts/header-menu.php
<?php

use app\admintheme\widgets\Menu;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\modules\admin\models\News;
use app\modules\blog\models\forms\NewsSearchForm;

$level1Count = 0;
$level2Count = 0;
$level3Count = 0;
$level4Count = 0;
$level5Count = 0;
$level6Count = 0;
$level7Count = 0;

if (Yii::$app->user->isGuest == false) {
    $levels = Yii::$app->user->identity->refer->getLevelsCount();

    $level1Count = $levels['1'];
    $level2Count = $levels['2'];
    $level3Count = $levels['3'];
    $level4Count = $levels['4'];
    $level5Count = $levels['5'];
    $level6Count = $levels['6'];
    $level7Count = $levels['7'];
}

$rubricsMenu = [];
$rubrics = \app\modules\admin\models\Rubric::find()->all();

foreach ($rubrics as $rubric){
    $rubricsMenu[] = [
        'label' => $rubric->name,
        'url' => ['/blog/news/index?NewsSearch[rubric]='.$rubric->id],
    ];
}

$notPublishedCount = News::find()->where(['or', ['status_published' => 0], ['status_published' => null]])->count();
$publishedCount = News::find()->where(['status_published' => 1])->count();
$search = new NewsSearchForm();

?>

<div id="sidebar" class="sidebar" style="padding-top: 0; z-index: 2000;">

    <div class="container">
        <div class="blog-header">
            <div class="blog-header__inner">
                <div class="blog-header__menu dropdown">
                    <button class="hamburger hamburger1" type="button" id="blogMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="bar bar1"></span>
                        <span class="bar bar2"></span>
                        <span class="bar bar3"></span>
                        <span class="bar bar4"></span>
                    </button>
                    <div class="blog-menu dropdown-menu" aria-labelledby="blogMenuButton">
                        <?php foreach($rubrics as $rubric): ?>
                            <?= Html::a(Html::encode($rubric->name), ['/blog/news/index', 'rubric' => $rubric->slug], ['class' => 'blog-menu__item']) ?>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="blog-header__logo">
                    <a href="/">
                        <img src="/img/mir-logo.png">
                    </a>
                </div>
                <div class="header-page__name">Блог МИРа</div>
                <div class="blog-header__search">
                    <?= Html::beginForm(Url::to(['/blog/news/index']), 'get') ?>
                        <div class="search-block">
                            <?= Html::activeTextInput($search, 'search', ['class' => 'header-search__input']) ?>
                        </div>
                    <?= Html::endForm() ?>
                </div>
                <a href=" https://mirumir24.ru/home#2" target="_blank" class="blog-header__text">
                    Стань автором и зарабатывай - участвуй в конкурсе!
                </a>
            </div>
        </div>

        
    </div>
</div>

modules/blog/views/layouts/header.php
<?php

use yii\helpers\Html;

?>

<div id="header" class="header navbar navbar-default navbar-fixed-top" style="min-height: unset; height: 41px;">
            <!-- begin container-fluid -->
            <div class="container-fluid">
                <!-- begin mobile sidebar expand / collapse button -->
                <div class="navbar-header">
                    <a href="<?=Yii::$app->homeUrl?>" class="navbar-brand">
                        <span class="navbar-logo"></span>
                        <?=Yii::$app->name?>
                    </a>
                    <button type="button" class="navbar-toggle" data-click="top-menu-toggled">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- end mobile sidebar expand / collapse button -->
                <ul class="header-menu">
                    <li><?= Html::a('Купоны', '#') ?></li>
                    <li><?= Html::a('Карта', '#') ?></li>
                    <li><?= Html::a('Тендеры', '#') ?></li>
                    <li><?= Html::a('Маркетплейс', '#') ?></li>
                    <li><?= Html::a('Доска', '#') ?></li>
                    <li><?= Html::a('Прокат', '#') ?></li>
                    <li><?= Html::a('Билеты', '#') ?></li>
                    <li><?= Html::a('Новости', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Погода', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('ТВ', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Радио', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Кино', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Игра', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Работа', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Знакоства', '#') ?></li>
                    <li class="mdsm-hidden"><?= Html::a('Офис', '#') ?></li>
                    <li><?= Html::a('Ещё', '#') ?></li>
                </ul>
                <?php if(Yii::$app->user->isGuest == false): ?>
                    <!-- begin header navigation right -->
                    <ul class="nav navbar-nav navbar-right" style="
    background: #f0da58;
    height: 41px;">
                        <li class="dropdown navbar-user">
                            <a id="btn-dropdown_header" href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" style="margin-top: -7px;">
                                <img src="/<?= Yii::$app->user->identity->getRealAvatarPath() ?>" data-role="avatar-view" alt="">
                                <?php
                                    $login = Yii::$app->user->identity->login;

                                    if(strlen($login) > 15){
                                        $login = iconv_substr ($login, 0, 13, "UTF-8").'...';
                                    }
                                ?>
                                <span class="hidden-xs"><?= $login?></span> <b class="caret"></b>
                            </a>
                            <div style="text-align: right;">
                                <ul class="dropdown-menu animated fadeInLeft">
									<?php if (Yii::$app->user->identity->login === 'admin'): ?>
                                    	<li> <?= Html::a('Раздел администратора', ['/admin/blog/index']) ?> </li>
									<?php endif; ?>
                                    <li> <?= Html::a('Счет', ['/accruals/index']) ?> </li>
                                    <li> <?= Html::a('Профиль', ['/user/profile']) ?> </li>
                                    	<li> <?= Html::a('Выйти', ['/site/logout'], ['data-method' => 'post']) ?> </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
<!--                    <ul class="nav navbar-nav navbar-right">-->
<!--                        <li class="dropdown navbar-user" style="margin-top: 12px;">-->
<!--                            <p>--><?php //echo Yii::$app->user->identity->selfRefHref;?><!--</p>-->
<!--                        </li>-->
<!--                    </ul>-->
                    <!-- end header navigation right -->
                <?php endif; ?>
            </div>
            <!-- end container-fluid -->
        </div>

modules/blog/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this \yii\web\View */
/* @var $content string */

//$isGuest = Yii::$app->user->isGuest;
//if($isGuest)
//    $theme = 'default';
//else
//    $theme = Yii::$app->user->identity->theme;


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    app\assets\ColorAdminAsset::register($this);

    // dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="https://miruwir.com/fav.png" type="image/x-icon">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <!-- ================== BEGIN BASE CSS STYLE ================== -->
        <?=$this->head()?>
        <link href="/theme/assets/css/theme/default.css" rel="stylesheet">
        <!-- ================== END BASE CSS STYLE ================== -->
        <script src="/theme/assets/plugins/jquery/jquery-1.9.1.min.js"></script>
<!--        <script src="/assets/pace/pace.min.js"></script>-->
    </head>
    <body class="blog-page">

    <?php $this->beginBody() ?>
        
    <?= $this->render('/layouts/blue_menu.php'); ?>
    <?= $this->render('/layouts/orange_menu.php'); ?>

    <div id="page-container" class="page-container main">
        <div class="main_main mCustomScrollbar" data-mcs-theme="minimal-dark">
            <div class="main__inner">
                <?= $this->render(
                   'header-menu.php',
                    ['directoryAsset' => $directoryAsset]
                ) ?>

                <?= $this->render(
                    'content.php',
                    ['content' => $content, 'directoryAsset' => $directoryAsset]
                ) ?>

                <?php /* $this->render(
                    'settings.php'
                ) */?>
            </div>
        </div>
    </div>



    <div class="d-none">
        <?php $avatar = new \app\models\forms\AvatarForm(); $avatarForm = ActiveForm::begin(['id' => 'avatar-form', 'action' => ['user/upload-avatar'], 'options' => ['enctype' => 'multipart/form-data']])  ?>

        <?= $avatarForm->field($avatar, 'file')->fileInput() ?>

        <?php ActiveForm::end() ?>
    </div>


    <?php $this->endBody() ?>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>


    <?=$this->render(
        'main-script.php'
    ) ?>
<style>
[title='Выберите формат файла для экспорта']{
    padding: 3px !important;
    padding-bottom: 2px !important;
}
</style>
<script>


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53034621-1', 'auto');
  ga('send', 'pageview');

</script>
    <script>

    </script>

    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

modules/blog/views/layouts/orange_menu.php
<div class="orange_menu">
    <div class="menu_und">  
        <a class="btn_menu_desc" href="#orange_menu_top"><div class="arrow_top">

            </div></a>
        <a class="btn_menu_desc" href="#orange_menu_bottom"><div class="arrow_bottom">

            </div></a>
        <div class="menu_carousel orange_menu_inner carousel owl-carousel owl-theme owl-loaded">
            <a href="/invite"><div class="menu_img green_menu"><img src="/img/orange_menu/1.png" alt="" title="Пригласить на сайт"></div></a>
            <!--<a href="/construction">  <div class="menu_img"><img src="/img/orange_menu/2.png" alt="" title="Уведомления"></div> </a>-->
            <a href="/construction">  <div class="menu_img"><img src="/img/orange_menu/raiting_yellow.png" alt="" title="Рейтинг"></div> </a>
            <a href="/construction">  <div class="menu_img"><img src="/img/orange_menu/news_yellow.png" alt="" title="Ленты"></div> </a> 
            <a href="/rod"><div id="dashboard_page" class="menu_img"><img src="/img/orange_menu/3.png" alt="" title="Родословная"></div></a>

            <a href="/site/profile">  <div id="user-profile" class="menu_img"><img src="/img/orange_menu/4.png" alt="" title="Профиль"></div> </a>
            <a href="/site/balance">  <div class="menu_img"><img src="/img/orange_menu/5.png" alt="" title="Счет"></div> </a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/6.png" alt="" title="Викистраница"></div> </a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/7.png" alt="" title="Фото"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/8.png" alt="" title="Видео"></div></a>


            <a href="/construction">  <div class="menu_img"><img src="/img/orange_menu/11.png" alt="" title="Блог"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/9.png" alt="" title="Связи"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/13.png" alt="" title="Клубы"></div></a>

            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/anceta_yellow.png" alt="" title="Анкета"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/rezume_yellow.png" alt="" title="Резюме"></div></a>

            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/shop_yellow.png" alt="" title="Магазин"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/10.png" alt="" title="Книга отзывов"></div></a>
            <a href="/construction">  <div class="menu_img"><img src="/img/orange_menu/14.png" alt="" title="Статистика"></div></a>
            <a href="/construction"> <div class="menu_img"><img src="/img/orange_menu/18.png" alt="" title="Офис"></div></a>
            <a data-method="post" href="/site/logout"> <div class="menu_img"><img src="/img/orange_menu/19.png" alt="" title="Выход"></div></a>

        </div>
    </div>
</div> 

modules/blog/views/layouts/settings.php
<?php

use app\models\UserSearch;
use yii\widgets\ActiveForm;
use app\helpers\AvatarResolver;
use yii\helpers\Html;


?>

    <?php

        $models = \app\models\News::find()->where(['status_published' => 1])->limit(10)->orderBy('count_news desc')->all();


    ?>

<div class="theme-panel active" style="top: 40px; height: 100%; z-index: 1; background: #efcb5b;">
<!--            <a href="javascript:;" data-click="theme-panel-expand" class="theme-collapse-btn"><i class="fa fa-cog"></i></a>-->

    <h5 style="font-weight: bold;">Популярные</h5>
    <hr style="margin-top: 5px; margin-bottom: 20px;">

<?php foreach ($models as $model): ?>

    <h5><?= Html::a($model->title, ['news/view', 'title' => $model->english_title], ['style' => 'font-weight: bold;']) ?></h5>
    <hr style="margin-top: 5px; margin-bottom: 5px;">

<?php endforeach; ?>

<!--        <div class="col-md-12">-->
<!--            <div class="col-md-3" style="padding-right: 0px!important;">-->
<!--                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQvpvNrkI5_zm4Kbdp6EYuLcoJ5Ije93aOxSpbOyiOdgbwFrA5y" alt="" style="border-radius: 100%; width: 55px; height: 55px; object-fit: cover;">-->
<!--            </div>-->
<!--            <div class="col-md-3" style="padding-right: 0px!important;">-->
<!--                <p style="color:black;">120 чел</p>-->
<!--                <p style="color:black;">$85 000</p>-->
<!--            </div>-->
<!--            <div class="col-md-3" style="padding-right: 0px!important;">-->
<!--                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQvpvNrkI5_zm4Kbdp6EYuLcoJ5Ije93aOxSpbOyiOdgbwFrA5y" alt="" style="border-radius: 100%; width: 55px; height: 55px; object-fit: cover;">-->
<!--            </div>-->
<!--            <div class="col-md-3" style="padding-right: 0px!important;">-->
<!--                <p style="color:black;">120 чел</p>-->
<!--                <p style="color:black;">$85 000</p>-->
<!--            </div>-->

    </div>
        <div class="">
            <div class="">
                <div class="row">


                </div>
            </div>
        </div>
    </div>
        </div>

<?php

$script = <<< JS

$('#user-list-form input').change(function(){
    $('#user-list-form').submit();
});

JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>